### ISSUE TITLE
Mac 2019.3.0f6 support inside 🤓

### ISSUE THREAD

**Issue by nicolasgramlich** [aevitas/unity-patch#14]
Purely for research purposes 🙃 

# Result

![image](https://user-images.githubusercontent.com/287060/73333456-a9983c80-421e-11ea-9349-ab5248d731de.png)

# Patch
```
diff --git a/Patcher/Program.cs b/Patcher/Program.cs
index c6ca3f5..d196c10 100644
--- a/Patcher/Program.cs
+++ b/Patcher/Program.cs
@@ -21,7 +21,14 @@ namespace Patcher
                         Version = "2019.1.0f2",
                         DarkPattern = new byte[] {0x75, 0x03, 0x41, 0x8b, 0x06, 0x48},
                         LightPattern = new byte[] {0x74, 0x03, 0x41, 0x8b, 0x06, 0x48}
+                    },
+                    new PatchInfo
+                    {
+                        Version = "2019.3.0f6",
+                        DarkPattern = new byte[] { 0x85, 0xD5, 0x00, 0x00, 0x00, 0x8B },
+                        LightPattern = new byte[] { 0x84, 0xD5, 0x00, 0x00, 0x00, 0x8B }
                     }
+
                 }
             },
             {
@@ -219,7 +226,7 @@ namespace Patcher
                         return;
                     }

-                    var themeByte = themeName == "dark" ? (byte)0x75 : (byte)0x74;
+                    var themeByte = themeName == "dark" ? (byte)0x85 : (byte)0x84;

                     foreach (var offset in lightOffsets)
                     {
```

# Suggestion
I'd suggest to maybe use the first byte out of the pattern instead of hardcoding 0x74 and 0x75 here?

https://github.com/aevitas/unity-patch/blob/27064edb488a8569838df073233ebfa1ffe5efda/Patcher/Program.cs#L222

# Question
Seems to work, but is it normal that multiple `Patching theme to dark..` occurrences are patched? 
```
./Patcher/bin/Debug/netcoreapp3.1/Patcher --mac --exe=/Applications/Unity/Hub/Editor/2019.3.0f6/Unity.app/Contents/MacOS/Unity --version=2019.3.0f6 --t=dark
Opening Unity executable from /Applications/Unity/Hub/Editor/2019.3.0f6/Unity.app/Contents/MacOS/Unity...
Creating backup..
Searching for theme offset..
Patching theme to dark..
Patching theme to dark..
Patching theme to dark..
Patching theme to dark..
Patching theme to dark..
Unity was successfully patched. Enjoy!
```

# Further Suggestion
Also if multiple instances of `Patching theme to dark..` are NOT supposed to be found, maybe log a warning that something might have gone broke?

**Comment by nicolasgramlich** [comment]
Btw, I used it for a couple of hours now without issues :)

**Comment by aevitas** [comment]
Hey Nicolas,

Thanks for opening this issue and providing the patterns for 2019.3 for Mac! If you want I can add them to the patcher, but you could also open up a pull request and add them yourself. Just let me know which you prefer.

Your suggestion makes complete sense. To be fair, I've been looking into approaching the offset finding and successive patching the past two days, because as it stands it can (and in your case, does) find multiple occurrences of the pattern we provide.

That's not bad per-se, because it can't determine which one is the actual location of the theme byte by itself, so the only valid approach at that point would be to just go ahead and patch all of them. It can cause some unexpected behaviour, but I don't think it will.

I'll have a look if I can make the patching process slightly more robust. I got myself a Mac recently, so I can experiment with it on that as well. :)

Let me know if you want me to make the changes to support 2019.3, or if you'd prefer to contribute them yourself!

**Comment by nicolasgramlich** [comment]
I can make a PR for this one, no problem. Hope I can get to it tonight 🤞 

Maybe we can just make the pattern longer to avoid finding dupes? And instead of writing just one byte, overwrite it with all the bytes from the other pattern. Could be more robust from the technical PoV, and a good trade of if it still achieves the same result of switching the theme properly.

I still think that adding the warning is a good idea, because we don't even know ourselves which ones is the correct occurrence :D

**Comment by nicolasgramlich** [comment]
Sorry for the delay. PR created :)
