### ISSUE TITLE
Theme offset not found in versions 2019.3.7f1 and 2019.3.8f1

### ISSUE THREAD

**Issue by rezgi** [aevitas/unity-patch#22]
**Description**
Sorry but it's a very noob question and couldn't find any other way to ask about it. I'm on OSX High Sierra and I didn't understand how to use your patch. I downloaded the repo as ZIP but couldn't figure out how to execute the terminal command line. Would you please tell me how to do that ?

Also, since I have Unity 2019.3.7f1, do you think I should give your patch a try ?

Thank you.

**Version Information**
OSX High Sierra 10.13.6
Unity 2019.3.7f1

**Diagnostics**
What does the patcher output instead of the expected behaviour?

**Arguments**
Please provide the exact command line arguments you are using the patcher with, e.g.:

`sudo ./linux-x64/Patcher -e=/path/to/Unity -t=dark -linux`

**Binaries**
If possible, provide a link to the Unity binary that corresponds with the version and OS you're using.

**Comment by aevitas** [comment]
Hi rezgi, thanks for your interest in the patch!

What you downloaded by getting the repository as a ZIP was the source files. You can compile them yourself, but you can also grab a binary release from the [release section](https://github.com/aevitas/unity-patch/releases) and run those directly.

Download the latest binary release and unzip it somewhere. Open up your terminal and `cd`  to the directory. If you unzipped it to your documents folder, you'd `cd ~/Documents/<patch folder>`.

The unzipped archive contains three folders for different operating systems. Because you're on Mac, you want to use the files in the `osx-x64` folder. Simply change directory by running `cd osx-x64` in your terminal.

Now that you have unzipped the patcher and pointed your terminal to the correct folder, you can run the patch by running the following command in your terminal:

```
Patcher -e=</path/to/unity/executable> -t=dark --version=2019.3.0f6 -mac
```

That should fire up the patch, and if all goes well, should change your Unity theme to dark.

Let me know if you still run into any issues!

**Comment by rezgi** [comment]
Thank you very much for your quick reply ! My bad I didn't understand that the binaries were in the release even though it was mentioned.

FYI I made it work by typing : `path/to/Patcher Patcher -e=...` since it was returning an error as it didn't find the command (I guess because it wasn't in the /bin)

So I tried with my Unity version 2019.3.7f1 and it gave me the following error : `Error: Could not find the theme offset in the specified executable!`

Here's the full command I entered : `Patcher -e=/Applications/Unity/Hub/Editor/2019.3.7f1/Unity.app/Contents/MacOS/Unity -v=2019.3.7f1  -t=dark --mac`

Then, as expected it prompted : `Could not find patch details for mac Unity version 2019.3.7f1 -- defaulting to version 2019.1.0f2.`

I guess you need to update your patch to include this version too right ? Should I follow your releases until you find a way to solve this ? Or maybe you want me to publish a new issue for this version ? Or rename this issue to "offset not found for 2019.3.7f1" ?

Again thank you very much for your help. I really want to care for my eyes while using Unity :D

**Comment by aevitas** [comment]
Could you try running it with the `--version="2019.3.0f6"` argument? It appears I haven't published a release since I fixed it reverting to the oldest version instead of the most recent one. 

Either way, there are usually not very many changes between minor versions of Unity, and the pattern for 2019.3.0f6 will probably work for your version as well.

If not, let me know and I'll dig deeper. :)

**Comment by rezgi** [comment]
I tried with the version argument but it returned the same error, I also tried on two versions : 3.7 and 3.8 (latest release) but same error. I also think the hex patterns should be the same in .3 versions but it's not working though, I've read in some forums that the patterns seem to be changing quite a lot and that the Unity Hub Update gives problems too.

Please let me know if you find anything ! Thanks a lot !

**Comment by dennym** [comment]
Run into the same issue and spend the last couple of hours to find the right disassembling tool to find the Symbol `::GetSkinIdx`. For windows and exe its rather easy to find the correct hex address but I have no idea how someone manged it in the past for the linux version.

Edit:
Ok so it seems that for windows its rather easy since it gets published with pdb files which map the function names to the compiled code so debugging is easier. Unfortunately this does not work for for linux since you have to run your own analysis which only returns obfuscated function and variable names.

**Comment by maximilianmaihoefner** [comment]
@aevitas @dennym Fyi, for me on MacOS using Unity 2019.3.9f1 the HexCode found in [https://github.com/aevitas/unity-patch/issues/14](url) applied using HexFiend works fine. So it doesn't look like the HexCodes themselves are wrong

**Comment by rezgi** [comment]
@maximilianmaihoefner Would you be kind enough to walk me through how to do it with HexFiend ? I tried by myself but Unity wasn't even opening after that. I looked into issue#14 and according to what's in this code :  `LightPattern = new byte[] { 0x84, 0xD5, 0x00, 0x00, 0x00, 0x8B }` 

I searched for it written like this : `84 D5 00 00 00 8B` and to replace it wit the hex found in `DarkPattern = new byte[] { 0x85, 0xD5, 0x00, 0x00, 0x00, 0x8B },` by writing it like this `85 D5 00 00 00 8B`

Then I clicked 'Replace' in HexFind and I guess it applied it seeing on the bar below 9 bytes out of .., but after that Unity 2019.3.8f1 didn't even open. I'm downloading the 3.9 now (heck, what's this release cycle ?).

Did I input the hex wrong ? What button should I click in HexFiend ? Replace ? Replace all ? 

Thank you very much.

**Comment by maximilianmaihoefner** [comment]
@rezgi Sure! I used the following steps on a fresh install of Unity 2019.3.9f1:
1. Open `/Applications/Unity/Hub/Editor/2019.3.9f1/`
2. Right click on `Unity.app` and select "Show Package Contents"
3. Then Navigate to `Contents/MacOS` and make a backup of the file called `Unity`
4. Open HexFiend and drop the original `Unity` file into HexFiend. (Make sure it doesn't say **READ-ONLY MODE** in the Application Bar)
5. Press Cmd+F to open the Find and Replace option.
6. Make sure you have "Hex" selected and not "Text" as the Find option.
7. Enter `84 D5 00 00 00 8B` in the Find field and `85 D5 00 00 00 8B` in the Replace field. (For me it has three matches at offset 10533284, 64989606 and 64991366)
8. Then use the "Replace All" Button to replace all matches and save the file.
9. Open Unity and enjoy your Dark Theme.

These steps work for me since Unity 2019.3.0f1, although I skipped some Versions in between but I would assume they work just fine using the same steps. Hope this helps!

**Comment by rezgi** [comment]
@maximilianmaihoefner It worked !!! Thank you very much for the detailed walkthrough, it's funny, before I did all of these steps, the only difference was that I pressed "Find and Replace" instead of "Replace All". My eyes are indebted to you !! Thanks !!

**Comment by aevitas** [comment]
> @aevitas @dennym Fyi, for me on MacOS using Unity 2019.3.9f1 the HexCode found in [https://github.com/aevitas/unity-patch/issues/14](url) applied using HexFiend works fine. So it doesn't look like the HexCodes themselves are wrong

Those changes went in through #16 , but it doesn't look like the patterns in the issue you linked and the ones that actually went into the code are the same. The main reason behind this was that the patch was finding multiple occurrences on MacOS, whereas it didn't on other OSes. Using this lengthened pattern would only find one match, but seeing as @rezgi is having trouble with it right now, it may not be patching the correct location.

If you guys can confirm that the shorter patterns above work, I think it would make sense to include those in the patcher instead. I'm fine doing those modifications myself, but if one of you wants to have a hack at it, let me know.

**Comment by aevitas** [comment]
> Run into the same issue and spend the last couple of hours to find the right disassembling tool to find the Symbol `::GetSkinIdx`. For windows and exe its rather easy to find the correct hex address but I have no idea how someone manged it in the past for the linux version.
> 
> Edit:
> Ok so it seems that for windows its rather easy since it gets published with pdb files which map the function names to the compiled code so debugging is easier. Unfortunately this does not work for for linux since you have to run your own analysis which only returns obfuscated function and variable names.

Linux is by far the most difficult platform to find them for, and it's the only one I haven't been able to find symbols for.

**Comment by dennym** [comment]
@aevitas Whats the approach for macos? Should be more similar to linux than to windows.

**Comment by maximilianmaihoefner** [comment]
@aevitas I went through the Unity Versions currently being reported as not working (e.g. 2019.3.4f1, 2019.3.7f1 and 2019.3.8f1), 2019.3.0f6 and 2019.3.9f1 and have found that the Hex `84 D5 00 00 00 8B 03` is matched in all of them and has only one match. I have opened #23 to apply the changes in the PatchInfo.

I also noticed that you have to either start Unity at least once before patching or open it twice to have the Dark Theme, I'm not quite sure why that is, it seems to have something todo with Unitys first time setup when starting a fresh install. If you want i can also add a Note regarding this Behaviour to the Readme.

**Comment by rezgi** [comment]
Just to add some info, I indeed needed to open Unity twice for it to have dark theme. I'm not sure how many occurrences of the hex were replaced in .3.9 since I just used 'Replace All' in HexFiend.

**Comment by aevitas** [comment]
Interesting, sounds like something that would be good to include in the readme. Thanks for the PR @maximilianmaihoefner -- it looks all good to me. Do you want to include the changes to the readme, or should those be included in a separate PR?

**Comment by maximilianmaihoefner** [comment]
@aevitas I updated the PR to include a Note in the Readme describing the Issue on macOS with the Themes getting mixed after patching. I could also add a picture if needed showing how it looks, but its pretty obvious when it happens. I also updated the Supported Versions to specify Unity 2019.3 on mac. If you want the wording changed let me know

**Comment by aevitas** [comment]
Thanks for all the work you've done! I've merged both pill requests and will draft a new release shortly.
