### ISSUE TITLE
Can you provide instructions on mac?

### ISSUE THREAD

**Issue by AnisimovArthur** [aevitas/unity-patch#3]

**Comment by aevitas** [comment]
Apologies for the late response - I didn't see this issue until now.

First off, grab [the latest release](https://github.com/aevitas/unity-patch/releases/tag/v1.02) from the releases page. If you have the dotnet runtime installed, you can grab the framework dependent release, otherwise grab the (fairly large) standalone version.

Once you've downloaded it, extract it to a folder on your Mac. For the sake of this post I'll assume it's extracted in `~/patcher`. Open a terminal and navigate to that folder.

The Mac binaries are in the `osx-x64` folder, so first `cd osx-64`. Afterwards, simply run `Patcher -e=/path/to/unity/executable -t=dark`, and the patcher should do the rest.

Now that I'm writing this I'm not sure the same executables are actually used on MacOS. I thought they were. but they may be different.

**Comment by AnisimovArthur** [comment]
Thanks for the answer!

After downloading the Patcher is not an executable.
What I've done:
1) `chmod +x Patcher`
2) run Script Editor `do shell script "/path/to/Patcher -e=/path/to/Unity -t=dark"`
Now it works.

But I got an error: 
> Creating backup..
Backup file created.. looks awake.
Searching for theme offset..
**Could not find the theme offset in the specified executable**

I tested it on  v2019.1.14f1. I can’t install exactly v2019.1.0f2, because of https://forum.unity.com/threads/installing-unity-on-macos-catalina.689089/
Is there support planned for later versions, e.g. 2019.2-2019.3?

**Comment by aevitas** [comment]
I'll keep supporting new builds of Unity as they are released. My daily driver is a Windows machine, so updates will be primarily for the Windows build of Unity.

The binaries for Mac are different from those on Windows, so the patcher won't be able to find the pattern described. I can add a Mac specific switch to the patcher once I get around to finding the correct patterns.

**Comment by AnisimovArthur** [comment]
Thanks!

**Comment by aevitas** [comment]
I've just committed some changes that introduce the `--mac` switch to the patcher. If you specify that flag, it should patch Unity for you.

I'll add a new release for it later on.
