### ISSUE TITLE
Unable to use patcher

### ISSUE THREAD

**Issue by rushilkoul** [aevitas/unity-patch#39]
i'm sorry if this is just a stupid question, but i can't seem to open the patcher.
according to the usage instructions there should be a patcher.app (please correct me if i've misunderstood something) but when i download the latest version 2.0.1 it just doesn't have any application in it; only a text file
![Screenshot 2020-05-22 at 5 12 09 PM](https://user-images.githubusercontent.com/64902289/82664457-62abd800-9c4f-11ea-95c2-d9f57ccd297a.png)

I downloaded the patch master; but i cannot seem to do anything with that too
![Screenshot 2020-05-22 at 5 14 13 PM](https://user-images.githubusercontent.com/64902289/82664600-abfc2780-9c4f-11ea-978b-b6c2ca5c1f5f.png)

Operating system: Mac
Unity version : 2019.014f

help pls

**Comment by maximilianmaihoefner** [comment]
There is no `.app` for the Patcher. The executable is the file just called `Patcher` which is shown in your first screenshot. To run it, open a Terminal Window and navigate to the `Patcher` file. Enter `chmod +x Patcher` to make the file executable and the run `./Patcher` to run the Patcher. From there the one screen instructions should help you patch Unity.

**Comment by aevitas** [comment]
Thanks @maximilianmaihoefner for jumping in! 👍 

@RushilKoul Did you manage to get the patcher working, or are you still experiencing difficulties?

**Comment by jacolee17** [comment]
Hi. I can't get this work in Terminal. I am confused by how to executed the Patcher. I used 'chmod +x Patcher' to make the patcher executable, and then tried using './Patcher' which shows permission denied, and using './osx-64/Patcher' which shows file not found. 

Can anyone provide a detailed instructions?  Thanks!

**Comment by maximilianmaihoefner** [comment]
@jacolee17 Sorry to hear that you are having issues running the Patcher. Here are more detailed instructions:
1. Download the lastest release (2.0.1 as of writing) osx-64.zip
2. Extract the Zip-Archive by double clicking it. The extracted Directory should contain a file called `Patcher` and one called `Patcher.pdb`.
    <img width="147" alt="Screenshot 2020-05-28 at 20 26 05" src="https://user-images.githubusercontent.com/5529459/83178883-7b216400-a121-11ea-972a-560199a4beca.png"> 
3. Open the Terminal.app, either by typing "Terminal" into Spotlight or by Navigating into your Application -> Utilities Directory and double click the Terminal.app
4. Navigate to the extracted directory (e.g ~/Downloads/osx-64) using `cd ~/Downloads/osx-64`.
5. Make the Patcher Binary executable using `chmod +x Patcher`. This should not show any Output.
6. Run the Patcher using `./Patcher`.
7. MacOS will tell you that `Patcher cannot be opened because the developer cannot be verified`. Click `Cancel`.
    <img width="418" alt="Screenshot 2020-05-28 at 20 19 35" src="https://user-images.githubusercontent.com/5529459/83179401-4a8dfa00-a122-11ea-82e5-5b89c5db54b5.png">
8. Open `System Preferences` and navigate to `Security & Privacy`. Click `Allow Anyway`. <img width="662" alt="Screenshot 2020-05-28 at 20 19 48" src="https://user-images.githubusercontent.com/5529459/83179550-77421180-a122-11ea-857f-892d70b3230b.png">
9. Go back to the Terminal and type `./Patcher` again.
10. MacOS will tell you `macOS cannot verify the developer of "Patcher". Are you sure you want to open it?`. Click `Open`.
    <img width="451" alt="Screenshot 2020-05-28 at 20 20 04" src="https://user-images.githubusercontent.com/5529459/83179803-cdaf5000-a122-11ea-8532-a410bbf8e527.png">
11. Choose from one of the displayed Unity Installations which one you want to patch.
12. Wait for the Patcher to complete.
13. Start Unity, it should display the Dark Theme. If not, restart Unity. After it opens up again it should work.

Here is my Terminal Output:
<img width="2034" alt="Screenshot 2020-05-28 at 20 20 38" src="https://user-images.githubusercontent.com/5529459/83179849-dd2e9900-a122-11ea-990e-a9c0c3cc53ce.png">

I hope this helps you. If you still have trouble running the Patcher let me know and I will try to help you as best I can.

**Comment by jacolee17** [comment]
@maximilianmaihoefner Thank you very much for the detailed instructions! I managed to execute the Patch file, however didn't see any available editor. I guess it's because my version(2019.3.8f) is not supported lol. 

Thank you again!

Here's my screenshoot.
<img width="549" alt="螢幕截圖 2020-05-28 下午6 03 16" src="https://user-images.githubusercontent.com/59125156/83198711-bdd94100-a10d-11ea-9b06-7a5ce8b2a09d.png">

**Comment by rushilkoul** [comment]
> Thanks @maximilianmaihoefner for jumping in! 👍
> 
> @RushilKoul Did you manage to get the patcher working, or are you still experiencing difficulties?

yes it works! my eyes thank you

**Comment by rushilkoul** [comment]
> There is no `.app` for the Patcher. The executable is the file just called `Patcher` which is shown in your first screenshot. To run it, open a Terminal Window and navigate to the `Patcher` file. Enter `chmod +x Patcher` to make the file executable and the run `./Patcher` to run the Patcher. From there the one screen instructions should help you patch Unity.

thank you

**Comment by maximilianmaihoefner** [comment]
@jacolee17 Unity 2019.3.8f is supported. The Error you are seeing is most likely because I missed a check when trying to find installed Unity Editors. Could you answer the following questions to help me nail down where the Issue comes from? Do you use Unity Hub? Where are your Unity Installations located (default is: /Applications/Unity/Hub/Editor)? Did you change anything manually in your installation Directory?

Anyways, until I fix that Issue you can still use the Patcher "the old way" by passing it the `-e` and `--version` arguments.
An example would be:
`./Patcher -e=/Applications/Unity/Hub/Editor/2019.3.8f1/Unity.app/Contents/MacOS/Unity --version=2019.3`
In case it doesn't properly detect your OS you can also pass `--mac`

**Comment by jacolee17** [comment]
@maximilianmaihoefner Thank you for your help! I notice my unity is installed under Applications/ , not /Applications/Unity/Hub/Editor. I use Unity Hub, and all settings are default. I tried your instructions, and Patcher can execute now, but still one more problem occurred lol.

The patcher can't find the theme.
<img width="823" alt="螢幕截圖 2020-05-29 上午9 54 56" src="https://user-images.githubusercontent.com/59125156/83267600-76e15f00-a192-11ea-9f83-94a244a1211b.png">

**Comment by maximilianmaihoefner** [comment]
@jacolee17 Thats strange. I just installed 2019.3.8f1 and it worked fine with the Command I mentioned above.
<img width="1745" alt="Screenshot 2020-05-29 at 18 03 22" src="https://user-images.githubusercontent.com/5529459/83280310-bf227080-a1d6-11ea-8578-92105af0e3d0.png">
Normally, if the patcher can't find the theme offset it is most likely looking for the wrong offset (e.g. looking for a different version of Unity, this is whats happening on your second run. Since we don't have a Version specified for `2019.3.8f` it is defaulting to 2020.2, the lastest version the Patcher supports).
You could try and reinstall Unity, but I don't know if it will help much. Also just to sanity check, is there actually Unity 2019.3.8f1 installed in that Directory? You could also try the Patcher with different Versions and see if it finds the offset for any of the other supported Versions (please refer to the Readme for a complete list of supported Versions).

**Comment by jacolee17** [comment]
I believe it is 2019.3.8f1. I will give it more tries later. Thank you very much

**Comment by jacolee17** [comment]
@maximilianmaihoefner I have a theory, maybe this has something to do with my Unity Hub's language setting. I am using Traditional Chinese now.

**Comment by maximilianmaihoefner** [comment]
@jacolee17 Hm, thats an interesting theory. Is the Unity Executable different when using Traditional Chinese? Could you run `sha1sum /Applications/2019.3.8f1/Unity.app/Contents/MacOS/Unity`, for me this Outputs: `cb3d5c121cad0b3ced4a767f1f54169ea97ee3b9`. Additionally the file size of the `Unity.app/Contents/MacOS/Unity` Executable for 2019.8.1f1 on my machine is `164746192` Bytes, you can check this using `ls -la /Applications/2019.3.8f1/Unity.app/Contents/MacOS/`.

**Comment by jacolee17** [comment]
lol mine is different from yours. @maximilianmaihoefner  
<img width="733" alt="螢幕截圖 2020-05-29 下午1 11 18" src="https://user-images.githubusercontent.com/59125156/83286444-f16ba800-a1ad-11ea-9f3f-e32c6cd420ff.png">

**Comment by maximilianmaihoefner** [comment]
@jacolee17 I tried changing my Hub language to Traditional Chinese but still got the same executable after reinstalling Unity. I also tried adding language packs and switching around modules but couldn't get a different Unity executable. Not sure what else could influence this.

If you want you can send me your executable and I can check for the theme offset and give you instructions on how to patch it.

**Comment by jacolee17** [comment]
@maximilianmaihoefner That's very nice of you! Thank you. I am sending u my executable file via GDrive.
[https://drive.google.com/file/d/1wL902EoeiilXMgUBTFeOm9cDYsbuE3kY/view?usp=sharing](url)

**Comment by maximilianmaihoefner** [comment]
You should be able to replace `84 EB 01 00 00 8B 03` with `85 EB 01 00 00 8B 03`. See my comment here: https://github.com/aevitas/unity-patch/issues/22#issuecomment-612363525 on how to do that.

I am still curious why it is different in this executable, i will investigate more and see if I can find anything.

**Comment by jacolee17** [comment]
@maximilianmaihoefner It finally worked! Thank you for your help!

**Comment by maximilianmaihoefner** [comment]
@aevitas I think everything here is resolved and the ticket can be closed.

I did try to poke around in the executable @jacolee17 provided, but was unable to figure out why it is different to the rest of the 2019.3 executables.

**Comment by aevitas** [comment]
Thanks for your help once again!
